version: '3.7'

volumes:
  mongo-db-volume:
    external: false

services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongo-db-volume:/data/db
